Tile attribution improvements (#309)
* Improve OSM attribution

- Use "(c) OpenStreetMap contributors" instead of "(c) OpenStreetMap"
  as suggested on https://www.openstreetmap.org/copyright
- Use https URL

* Update HOTOSM attribution

Use the same attribution as openstreetmap.org for the HOT tiles.

* Update Mapbox attribution

See https://docs.mapbox.com/help/how-mapbox-works/attribution/#text-attribution

* Update eslint-plugin-html

This fixes the following error:
   TypeError: Cannot read property 'define' of undefined
See https://github.com/BenoitZugmeyer/eslint-plugin-html/issues/113

+ add node_modules to .gitignore